Fix usage vcpkg for windows and add cmake preset for vscode
MihailRis/VoxelEngine-Cpp pull request #414
Opened 2024-12-14 23:46 UTC by Ygrik2003

Добавил пресет для интеграции с VSCode и подправил cmake для правильной работы vcpkg

Теперь не нужно 2 раза вызывать конфигурацию. Избавился от параметра VOXELENGINE_BUILD_WINDOWS_VCPKG в CMake. Теперь по дефолту windows билд собирается с vcpkg

Избавился от vcpkg загрузки из CMake, теперь есть ограничения:
1. Должна быть выставлена переменная среды VCPKG_ROOT, указывающая на корень установки vcpkg
2. Собственно сам vcpkg нужно ставить самому как в [доке](https://learn.microsoft.com/en-us/vcpkg/users/buildsystems/cmake-integration)

За одно подправил деплой ресов, теперь он всегда будет работать под все платформы без проблем и костылей

Единственное, не уверен, что не сломал сборку windows-clang.yml, нужно перепроверить, возможно нужно делать экспорт полного пути к vcpkg .github\workflows\windows-clang.yml:46
```
export VCPKG_ROOT=./vcpkg
export VCPKG_DEFAULT_TRIPLET=x64-mingw-static
export VCPKG_DEFAULT_HOST_TRIPLET=x64-mingw-static
mkdir build
cd build
cmake --preset default-windows -G "MinGW Makefiles" -DVCPKG_TARGET_TRIPLET=x64-mingw-static -DCMAKE_BUILD_TYPE=Release ..
cmake --build . --config Release
```
В любом случае нужно перепроверить этот билд

2024-12-17 07:59 UTC, Ygrik2003 commented
К слову, потыкался чутка с vcpkg, оказывается, если запускаться в дев терминале вижлы, то там прокидывается переменная VCPKG_ROOT автоматически, так что можно еще будет дописать в readme, вечером закомитаю

2024-12-18 20:39 UTC, MihailRis commented
Обновил настройки workflow в ветке, чтобы запускались проверки в PR. Нужно вытянуть изменения из headless-mode.

2024-12-20 14:22 UTC, Ygrik2003 commented
Еще немного потрогал Github Actions, теперь билды будут работать прямо из пресетов, что должно чутка облегчить работу с workflows при работе с флагами 
Сделал clang сборку через генератор Ninja Multi-Config
Переделал подключение vcpkg в github actions в соответствии с [докой](https://learn.microsoft.com/en-us/vcpkg/consume/binary-caching-github-packages?pivots=windows-runner)
в общем нужно перепроверить билды

2024-12-20 21:56 UTC, Ygrik2003 commented
![image](https://github.com/user-attachments/assets/b4551f16-2cb4-4fbb-bb8f-a8c0d25df9fa)

2024-12-20 22:11 UTC, Ygrik2003 commented
Отвалились vctest и неправильные пути для msys2 под clang, завтра-послезавтра гляну

2024-12-20 22:35 UTC, Ygrik2003 commented
Короче можно попробовать первоначальный фикс с VCPKG_ROOT: ./vcpkg
если не сработает, то нужно будет думать

2024-12-22 01:02 UTC, Ygrik2003 commented
Короче намучался с MSYS2, судя по всему, он нужен был для того, что бы cmake по умолчанию находил clang. Так как я дописал cmake и теперь компилятор выбирается пресетом, я выкосил msys2 из windows-clang и теперь как и обычный windows конфиг, собирается через pwsh
Если в целом возражений нет, то ПР готов

2024-12-22 02:25 UTC, MihailRis requested changes

2024-12-22 02:25 UTC, MihailRis commented on .github/workflows/windows-clang.yml
> +          cp C:/Windows/System32/msvcp140.dll packaged/Release/msvcp140.dll
К чему в Clang сборке эта строка? (50)
Кроме того, линковка теперь динамическая, при том, что должна быть статическая.

2024-12-22 02:25 UTC, MihailRis commented on .github/workflows/windows-clang.yml
> +          cp C:/Windows/System32/msvcp140.dll packaged/Release/msvcp140.dll
В релизе отсутствует vctest.exe

2024-12-22 02:25 UTC, MihailRis commented on .github/workflows/windows-clang.yml
> +          cp C:/Windows/System32/msvcp140.dll packaged/Release/msvcp140.dll
Внутри, вместо VoxelCore.exe лежит VoxelEngine.exe, несмотря на строку 51.

2024-12-22 02:25 UTC, MihailRis commented on .github/workflows/windows-clang.yml
> +          cp C:/Windows/System32/msvcp140.dll packaged/Release/msvcp140.dll
Кроме того, exe имеет динамическую зависимость в msvcp140.dll, которой в Clang-сборке быть не должно

2024-12-22 11:17 UTC, Ygrik2003 commented on .github/workflows/windows-clang.yml
> +          cp C:/Windows/System32/msvcp140.dll packaged/Release/msvcp140.dll
По поводу msvcp140, это как раз таки одна из особенностей отказа от MSYS2
Дело в том, что msys2 и Cygwin поставляют свой Clang, который зависит от своих либ
Тот Clang, который я заюзал (LLVM), он юзает такой же рантайм, как и msvc. Что касательно линковки, то необходимый набор dll'ок слегка отличается, но msvcp140.dll все же присутствует
Нашел [такую статью](https://blog.conan.io/2022/10/13/Different-flavors-Clang-compiler-Windows.html), которая частично объясняет происходящее. 

А вообще, если у человека не установлен microsoft visual c++ redistributable (обычно устанавливается автоматически при скачивании некоторых игр в стиме), то игра вообще не запустится

2024-12-22 13:30 UTC, Ygrik2003 commented on .github/workflows/windows-clang.yml
> +          cp C:/Windows/System32/msvcp140.dll packaged/Release/msvcp140.dll
Поправил остальное, деплоилась не там папка

2024-12-22 13:32 UTC, Ygrik2003 commented
@MihailRis  А зачем вообще нужно переименование VoxelEngine в VoxelCore?

2024-12-24 04:38 UTC, MihailRis commented on .github/workflows/windows-clang.yml
> +          cp C:/Windows/System32/msvcp140.dll packaged/Release/msvcp140.dll
Основной вопрос в статической линковке, что была реализована в workflow ранее, где исключением был только lua51.dll.

2024-12-25 00:14 UTC, Ygrik2003 commented on .github/workflows/windows-clang.yml
> +          cp C:/Windows/System32/msvcp140.dll packaged/Release/msvcp140.dll
В общем мне удалось добиться статической линковки, в том числе и для lua51, @MihailRis с этим проблем нет?
![{B6F19D82-2F7C-4887-8837-DCD26F91DAC7}](https://github.com/user-attachments/assets/6d6f8b4d-953e-4434-b8e4-277eac452064)

2024-12-25 12:47 UTC, MihailRis commented
Добавил тест производительности.
Нужно проверить перед слиянием.

2024-12-25 12:52 UTC, Ygrik2003 commented
Подмержил

2024-12-25 13:19 UTC, MihailRis commented on CMakeLists.txt
> +    set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
Clang сборка была добавлена исключительно из-за лучшей производительности генерируемого кода, в сравнении с MSVC.
От теста `perftest` (можно найти в логе как `executing test "perftest"`) в clang сборке ожидается время `[time mcs] xxx` в ~2 раза меньшее, чем в MSVC, что можно увидеть в ветке `headless-mode`.

2024-12-25 13:23 UTC, Ygrik2003 commented on CMakeLists.txt
> +    set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
Окей, гляну

2024-12-25 16:13 UTC, Ygrik2003 commented
Откатился до msys2, перфа восстановилась, видимо нужно играть с флагами llvm clang'а (хотя теперь я и вовсе не уверен, что можно достичь такой перфы, зная, что llvm clang все равно юзает MSVC), а для этого хотелось бы профилировщик заиметь, что бы хотя бы понимать, в каком направлении можно двигаться

2024-12-26 16:23 UTC, MihailRis approved these changes

2024-12-26 16:58 UTC, merged